version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.7.10"
      FORGEVERSION: "10.13.4.1614"
      ENFORCE_WHITELIST: 0
      ONLINE_MODE: 0
      SERVER_NAME: "darkwind's technomagic server!"
      MOTD: "Welcome to darkwind's place to have fun!"
      ALLOW_NETHER: 1
      TYPE: "FORGE"
      OPS: "${admin}"
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
      - ./mods:/data/mods
      - ./config:/data/config
      - ./ForgeEssentials:/data/ForgeEssentials
